version: "1.0"

services:
  vscode-pytorch:
    image: spheronfdn/vscode-pytorch:latest
    pull_policy: IfNotPresent
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=test
      - SUDO_PASSWORD=test
      - DEFAULT_WORKSPACE=/config/workspace
    params:
      storage:
        default:
          mount: /mnt/data
          readOnly: false
profiles:
  name: vscode-pytorch
  duration: 1h
  mode: provider
  compute:
    vscode-pytorch:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          name: "default"
          size: 120Gi
          attributes:
            persistent: true
            class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      pricing:
        vscode-pytorch:
          token: uSPON
          amount: 1.1

deployment:
  vscode-pytorch:
    westcoast:
      profile: vscode-pytorch
      count: 1
