version: "1.0"

services:
  py-cuda:
    image: spheronfdn/jupyter-notebook:pytorch-2.4.1-cuda-enabled
    pull_policy: IfNotPresent
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
    env:
      - JUPYTER_TOKEN=test
profiles:
  name: py-cuda
  duration: 2h
  mode: provider
  compute:
    py-cuda:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 200Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      pricing:
        py-cuda:
          token: uSPON
          amount: 1

deployment:
  py-cuda:
    westcoast:
      profile: py-cuda
      count: 1
