version: "1.0"

services:
  tensorflow-server:
    image: spheronfdn/tensorflow:latest-gpu
    pull_policy: Always
    expose:
      - port: 22
        as: 22
        to:
          - global: true
    params:
      storage:
        default:
          mount: /mnt/data
          readOnly: false
profiles:
  name: tensorflow-server
  duration: 1h
  mode: provider
  compute:
    tensorflow-server:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          name: "default"
          size: 200Gi
          attributes:
            persistent: true
            class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      pricing:
        tensorflow-server:
          token: uSPON
          amount: 1

deployment:
  tensorflow-server:
    westcoast:
      profile: tensorflow-server
      count: 1
