version: "1.0"

services:
  ollama:
    image: ghcr.io/open-webui/open-webui:ollama
    pull_policy: IfNotPresent
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
profiles:
  name: ollama
  duration: 2h
  mode: fizz
  compute:
    ollama:
      resources:
        cpu:
          units: 6
        memory:
          size: 16Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      pricing:
        ollama:
          token: CST
          amount: 1

deployment:
  ollama:
    westcoast:
      profile: ollama
      count: 1
