version: '3.8'

services:
  miner:
    build:
      context: .
      dockerfile: Dockerfile
    image: spheronnetwork/sn-bitmind:v1.0.0
    environment:
      - COLDKEY_MNEMONIC=""
      - HOTKEY_MNEMONIC=""
    restart: unless-stopped
