version: "1.0"

services:
  sn9-pretraining:
    image: spheronnetwork/sn-bitmind:v1.0.0
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 8091
        as: 8091
        to:
          - global: true
    env:
      - COLDKEY_MNEMONIC=""
      - HOTKEY_MNEMONIC=""

profiles:
  name: sn9-pretraining
  duration: 2h
  mode: provider
  tier:
    - community
  compute:
    sn9-pretraining:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 200Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        sn9-pretraining:
          token: USDT
          amount: 10

deployment:
  sn9-pretraining:
    westcoast:
      profile: sn9-pretraining
      count: 1
