version: "1.0"

services:
  unsloth-finetuning:
    image: spheronfdn/unsloth-finetuning:cuda12-pytorch
    pull_policy: IfNotPresent
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
    env:
      - JUPYTER_TOKEN=test
profiles:
  name: unsloth-finetuning
  duration: 1h
  mode: provider
  compute:
    unsloth-finetuning:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 200Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx6000-ada
  placement:
    westcoast:
      pricing:
        unsloth-finetuning:
          token: uSPON
          amount: 2

deployment:
  unsloth-finetuning:
    westcoast:
      profile: unsloth-finetuning
      count: 1
