version: "1.0"

services:
  ubuntu24-server:
    image: spheronfdn/ubuntu:22.04
    pull_policy: Always
    expose:
      - port: 22
        as: 22
        to:
          - global: true    
profiles:
  name: ubuntu24-server
  duration: 1h
  mode: provider
  compute:
    ubuntu24-server:
      resources:
        cpu:
          units: 4
        memory:
          size: 4Gi
        storage:
          - size: 4Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: t1000
  placement:
    westcoast:
      attributes:
        desired_provider: "0xa9322C6fA6978c4C87d3F654B86B67E55E03E0D0"
      pricing:
        ubuntu24-server:
          token: uSPON
          amount: 10

deployment:
  ubuntu24-server:
    westcoast:
      profile: ubuntu24-server
      count: 1