version: "1.0"

services:
  ubuntu22-server:
    image: spheronfdn/ubuntu:22.04
    pull_policy: Always
    expose:
      - port: 22
        as: 22
        to:
          - global: true
profiles:
  name: ubuntu22-server
  duration: 1h
  mode: provider
  compute:
    ubuntu22-server:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 100Gi
  placement:
    westcoast:
      pricing:
        ubuntu22-server:
          token: uSPON
          amount: 1
deployment:
  ubuntu22-server:
    westcoast:
      profile: ubuntu22-server
      count: 1
